### ISSUE TITLE
Terminado infrme de la práctica de Implementing Search in the Jekyll Web Site

### ISSUE THREAD

**Issue by Gia-ui** [ULL-ESIT-DMSI-2223/intro2sd-gianmarco-corbo-alu0101134741#10]
@crguezl terminado. Creado un post en la página con el informe.

**Comment by crguezl** [comment]
@Gia-ui 

Feliz 🎄 

Hay errores en el código desplegado en GitHub:

<img width="848" alt="Captura de pantalla 2022-12-28 a las 19 40 26" src="https://user-images.githubusercontent.com/1142554/209864086-bb6ecbec-c378-4e26-abb7-489188f2a3d6.png">

**Comment by Gia-ui** [comment]
@crguezl Problema solucionado, aunque para resolverlo he tenido que deshacer los cambios que había añadido para que el constructor de JekyllSearch reciba en un objeto los argumentos, en vez de posicionalmente. Encontré el problema y lo había corregido, pero por alguna razón github-pages, a la hora de cargar la página en el navegador, cargaba siempre el mismo fichero search.js, mientras que sí cargaba la versión de search.md corregida. Pero en la rama de github-pages sí aparecía el fichero correcto. Probé borrando la caché del navegador o usando otro diferente, pero seguía el mismo problema, por lo que al final opté por borrar por completo los cambios para ese apartado y devolverlo a como era el código al comienzo.

**Comment by crguezl** [comment]
@Gia-ui 
🆗 
👍
